import { FoodItem } from './ui/FoodList';

const generateFakeItems = (): FoodItem[] => {
  return [
    {
      name: 'Manzanas Gala',
      category: 'Frutas',
      amount: '1',
      unit: 'kg',
      expirationDate: '2024-10-05',
      dateAdded: '2024-09-25',
      location: 'Cajón de frutas',
    },
    {
      name: 'Espinacas frescas',
      category: 'Verduras',
      amount: '2',
      unit: 'manojo(s)',
      expirationDate: '2024-09-30',
      dateAdded: '2024-09-25',
      location: 'Cajón de verduras',
    },
    {
      name: 'Pechuga de pollo',
      category: 'Carnes',
      amount: '500',
      unit: 'g',
      expirationDate: '2024-10-02',
      dateAdded: '2024-09-25',
      location: 'Refrigerador',
    },
    {
      name: 'Salmón ahumado',
      category: 'Pescados y mariscos',
      amount: '200',
      unit: 'g',
      expirationDate: '2024-10-01',
      dateAdded: '2024-09-25',
      location: 'Refrigerador',
    },
    {
      name: 'Yogur natural',
      category: 'Lácteos',
      amount: '1',
      unit: 'L',
      expirationDate: '2024-10-10',
      dateAdded: '2024-09-25',
      location: 'Puerta del refrigerador',
    },
    {
      name: 'Huevos orgánicos',
      category: 'Huevos',
      amount: '1',
      unit: 'docena(s)',
      expirationDate: '2024-10-15',
      dateAdded: '2024-09-25',
      location: 'Puerta del refrigerador',
    },
    {
      name: 'Avena integral',
      category: 'Cereales',
      amount: '500',
      unit: 'g',
      expirationDate: '2025-03-25',
      dateAdded: '2024-09-25',
      location: 'Alacena',
    },
    {
      name: 'Lentejas',
      category: 'Legumbres',
      amount: '1',
      unit: 'kg',
      expirationDate: '2025-09-25',
      dateAdded: '2024-09-25',
      location: 'Despensa',
    },
    {
      name: 'Almendras crudas',
      category: 'Frutos secos',
      amount: '250',
      unit: 'g',
      expirationDate: '2025-01-25',
      dateAdded: '2024-09-25',
      location: 'Alacena',
    },
    {
      name: 'Albahaca fresca',
      category: 'Especias y hierbas',
      amount: '1',
      unit: 'manojo(s)',
      expirationDate: '2024-10-02',
      dateAdded: '2024-09-25',
      location: 'Refrigerador',
    },
    {
      name: 'Aceite de oliva extra virgen',
      category: 'Aceites y grasas',
      amount: '750',
      unit: 'mL',
      expirationDate: '2025-09-25',
      dateAdded: '2024-09-25',
      location: 'Alacena',
    },
    {
      name: 'Agua mineral',
      category: 'Bebidas',
      amount: '6',
      unit: 'botella(s)',
      expirationDate: '2025-09-25',
      dateAdded: '2024-09-25',
      location: 'Despensa',
    },
    {
      name: 'Chips de tortilla',
      category: 'Snacks',
      amount: '200',
      unit: 'g',
      expirationDate: '2024-11-25',
      dateAdded: '2024-09-25',
      location: 'Alacena',
    },
    {
      name: 'Pan integral',
      category: 'Panadería',
      amount: '1',
      unit: 'pieza(s)',
      expirationDate: '2024-10-02',
      dateAdded: '2024-09-25',
      location: 'Aparador',
    },
    {
      name: 'Helado de vainilla',
      category: 'Dulces y postres',
      amount: '1',
      unit: 'L',
      expirationDate: '2024-12-25',
      dateAdded: '2024-09-25',
      location: 'Congelador',
    },
    {
      name: 'Guisantes congelados',
      category: 'Congelados',
      amount: '500',
      unit: 'g',
      expirationDate: '2025-03-25',
      dateAdded: '2024-09-25',
      location: 'Congelador',
    },
    {
      name: 'Atún en lata',
      category: 'Enlatados',
      amount: '3',
      unit: 'lata(s)',
      expirationDate: '2026-09-25',
      dateAdded: '2024-09-25',
      location: 'Alacena',
    },
    {
      name: 'Salsa de tomate',
      category: 'Salsas y condimentos',
      amount: '500',
      unit: 'mL',
      expirationDate: '2025-03-25',
      dateAdded: '2024-09-25',
      location: 'Alacena',
    },
    {
      name: 'Espaguetis',
      category: 'Pastas',
      amount: '500',
      unit: 'g',
      expirationDate: '2025-09-25',
      dateAdded: '2024-09-25',
      location: 'Alacena',
    },
    {
      name: 'Tofu firme',
      category: 'Productos veganos',
      amount: '400',
      unit: 'g',
      expirationDate: '2024-10-10',
      dateAdded: '2024-09-25',
      location: 'Refrigerador',
    },
    {
      name: 'Papilla de frutas',
      category: 'Alimentos para bebés',
      amount: '4',
      unit: 'frasco(s)',
      expirationDate: '2025-03-25',
      dateAdded: '2024-09-25',
      location: 'Alacena',
    },
    {
      name: 'Lasaña congelada',
      category: 'Comida preparada',
      amount: '1',
      unit: 'pieza(s)',
      expirationDate: '2024-12-25',
      dateAdded: '2024-09-25',
      location: 'Congelador',
    },
    {
      name: 'Vino tinto Rioja',
      category: 'Bebidas',
      amount: '2',
      unit: 'botella(s)',
      expirationDate: '2026-09-25',
      dateAdded: '2024-09-25',
      location: 'Vinero / bar',
    },
  ];
};

const fakeItems = generateFakeItems();

export default fakeItems;
